debug: false
healthcheck: true

mqtt:
  base_topic: rfxcom2mqtt
  server: tcp://<IP ADDRESS>
  username: <USERNAME>
  password: <PASSWORD>
  qos: 0
  retain: false

rfxcom:
  usbport: /dev/ttyUSB0
  debug: false
  transmit:
    repeat: 4
  receive:
    - temperaturehumidity1
    - homeconfort
    - lighting1
    - lighting2
    - lighting3
    - lighting4
    - remote
    - security1

devices:
  - id: '1001010/1'
    friendlyName: 'CucuDimmer'

  - id: '0x012E00FF'
    friendlyName: 'Living Room switch'

  - id: '0x00ED400F/1'
    friendlyName: 'Light 1'
    type: lighting1

  - id: '0x00ED400F/2'
    friendlyName: 'Light 2'

  - id: '0x00ED400F/3'
    friendlyName: 'Light 3'

  - id: '0x3D090F'
    friendlyName: 'Switch1'
    
  - id: '0x3D090E'
    friendlyName: 'Switch2'

  - id: '071a000000000a03'
    options: {
      'venetian_blind_mode': 'US'
    }