version: "3.8"

services: 
  rfxcom2mqtt:
    container_name: rfxcom2mqtt
    build: ./
    volumes:
      - ./:/app/data
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0
    environment:
      - TZ=Europe/London
    restart: unless-stopped
